### ISSUE TITLE
[DOC] Entrevista

### ISSUE THREAD

**Issue by RCristyan** [UnBArqDsw/2020.1_G7_TCM#10]
### Descrição
A entrevista é uma técnica de elicitação de requisitos que consiste em extrair informações de uma pessoa, podendo ser um stakeholder, um interessado no projeto ou possível usuário.

### Coisas a se fazer
- [x] Introdução
- [x] Roteiro
- [x] Entrevistas
- [x] Requisitos Elicitados
- [x] Versionamento
- [x] Referências Bibliográficas

### Referências
https://requisitos-de-software.github.io/2019.2-Waze/Entrevista/
https://www.devmedia.com.br/tecnicas-para-levantamento-de-requisitos/9151

**Comment by MoacirMSJ** [comment]
No tópico Metodologia é dito: "...optamos por seguir um modelo de entrevista fechada onde terá uma série de perguntas pré-definidas..." e na entrevista o entrevistador teve bastante flexibilidade, realizando  perguntas além das pré-definidas, sendo assim entrevista pode ser caracterizada como **não estruturada ou aberta**.
Há uma pequena fuga do padrão no requisito ENT016  o '0'.

**Comment by jpcirqueira** [comment]
@MoacirMSJ Concordo com você, fiz alterações necessarias nos topicos apresentados.
