### ISSUE TITLE
[DOC] Observação

### ISSUE THREAD

**Issue by RCristyan** [UnBArqDsw/2020.1_G7_TCM#11]
### Descrição
A observação é uma técnica de elicitação de requisitos que consiste em analisar o funcionamento de softwares semelhantes, e assim ter uma ideia do que é interessante para o nosso projeto e o que é ruim.

### Coisas a se fazer
- [x] Introdução
- [x] Descrição dos softwares observados
- [x] Requisitos Elicitados
- [x] Versionamento
- [x] Referências Bibliográficas

### Referências
https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-observacao

**Comment by jpcirqueira** [comment]
Fiz a revisão do documnto, acredito que o seguinte topico devem ser refatorado:
- No topico de análise da avaliação 1 a seguinte frase me parece incongruente:  então a eficiência da tarefa foi satisfatória para campeonatos pequenos, mas mediana para campeonatos pequenos.
(@RCristyan @MoacirMSJ )

**Comment by MoacirMSJ** [comment]
Correções realizadas e foram adicionadas referências do aplicativo utilizado na observação.
