### ISSUE TITLE
Prototipação

### ISSUE THREAD

**Issue by RCristyan** [UnBArqDsw/2020.1_G7_TCM#13]
### Descrição
Criar o primeiro protótipo do projeto

### Coisas a se fazer
- [x] Introdução
- [x] Protótipo
- [x] Versionamento
- [x] Referências Bibliográficas

**Comment by jpcirqueira** [comment]
Fiz a revisão do documento.O documento está bom, porém tem alguns erros ortográficos.
(@MatheusEstanislau @lucasA27 )

**Comment by lucasA27** [comment]
O documento será refatorado para corrigir os erros ortográficos.

**Comment by MatheusEstanislau** [comment]
@jpcirqueira O Documento foi alterado de acordo com as normas gramaticais, depois consegue verificar o documento novamente ?
