### ISSUE TITLE
[DOC]Documentar Léxicos

### ISSUE THREAD

**Issue by MatheusEstanislau** [UnBArqDsw/2020.1_G7_TCM#14]
### Descrição
Identificação de palavras ou frases peculiares ao meio social da aplicação sob estudo.

### Coisas a se fazer
- [x] Produção do documento contendo os  léxicos do projeto

**Comment by MoacirMSJ** [comment]
Segundo o material utilizado como referência do documento [LAL](http://www-di.inf.puc-rio.br/~julio/lal.pdf), 
nas regras dos tipos(página 13)   tem as noções: 
 - **verbo** tem a noção de " Quem realiza, quando acontece..." 
 -  **Sujeito** "Quem é o sujeito"
 - **Objeto**  "Definir objeto e identificar outros..."

No documento o usuário e o moderador são  tipados como objeto.

- L16-  Foi repetido

Além disso há pequenos erros de ortografia nos tópicos:
- L07 - Noção
- L15- Noção  
- L16-  Impacto

**Comment by jpcirqueira** [comment]
@MoacirMSJ  fiz alterações necessarias nos topicos apresentados.
