### ISSUE TITLE
[DOC]Design Sprint

### ISSUE THREAD

**Issue by MatheusEstanislau** [UnBArqDsw/2020.1_G7_TCM#15]
### Descrição
Elaboração do documento de design sprint

### Coisas a se fazer
- [ ] Desenvolvimento do documento de design sprint contendo o planejamento e fases.
- [ ] Definir Unpack
- [ ] Definir Sketch
- [ ] Definir Decision
- [ ] Definir Prototype

**Comment by jpcirqueira** [comment]
Por motivo de gerencia a equipe não conseguiu realizar o design sprint.
