### ISSUE TITLE
[DOC]Documentação da metodologia

### ISSUE THREAD

**Issue by MatheusEstanislau** [UnBArqDsw/2020.1_G7_TCM#16]
### Descrição
Especificar metodologia que será utilizada durante o projeto

### Coisas a se fazer
- [x] Documento para especificação da metodologia
- [x] Elaborar cronograma de acordo com a metodologia

**Comment by RCristyan** [comment]
Fiz a revisão do documento de metodologia e observei que estava com qualidade muito boa e atende as expectativas para a apresentação. Houveram alguns pequenos erros ortográficos mas foram facilmente corrigidos. 

Entretanto, um dos tópicos da RUP estava incompleto:

![image](https://user-images.githubusercontent.com/39436190/92654565-62028480-f2c6-11ea-93c1-83c777f626c8.png)

Um dos autores deve terminar o tópico ou então removê-lo do documento, se necessário.
