### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EsioFreitas** [UnBArqDsw/2020.1_G7_TCM#18]
**Visão geral**
Muito bom o historico de edição e referencia. Mas recomendo colocar o historico de edição no começo do documento. Falta versionamento nos documentos de vcs! Qualidade e melhor que quantidade! Alem disso, vcs precisam colocar o nome de quem fez os documentos.

**Documento de Visão**
Simples, mas exato. Parabens! Consegui entender a ideia da aplicação.

**Brainstorm** 
Muito legal!

**Estrutura Analítica de Riscos - EAR**
Gostei do artefato! Principalmente na situação da matéria. Vcs vão seguir mapeando os riscos até o final do projeto?

**Plano de gerenciamento** 
Só 18,75 a hora?! É trabalho escravo? kkkkk Muito legal o documento! 

**RP**
Está com cara de mapa mental. 

**5W2H**
O documento está falando da equipe de desenvolvimento. O certo seria falar do produto. 

**Design Sprint** 
Muito bom, mas ta incompleto. Caso estejam no processo, desconsidere. 

**Entrevista**
Muito legal! Imagino que estaja no processo ainda ne?

**Observação**
Muito bom!

**Mapas Mentais**
Muito bom

**Léxico** 
Muito bom!/

**Gerenciamento do cronograma do projeto**
Nao consegui ver o cronograma

**Personas**
Gostei da ideia, mas achei o documento fraco. Como ele acrescentou na ideia de projeto?

**Comment by jpcirqueira** [comment]
Esio, obrigado pelo feedback. Iremos fazer os ajustes necessarios de acordo com seu feedback.
