### ISSUE TITLE
[DOC] Glossario

### ISSUE THREAD

**Issue by jpcirqueira** [UnBArqDsw/2020.1_G7_TCM#19]
### Glossario
Elaborar documento de glossario.

### Coisas a se fazer
- [ ] Introdução
- [ ] Tópico 1
- [ ] Versionamento
- [ ] Referências Bibliográficas

**Comment by RCristyan** [comment]
De acordo com o feedback da professora, não será necessário implementar o glossário pois já temos os léxicos.
