### ISSUE TITLE
[DOC] Revisar Documentos 

### ISSUE THREAD

**Issue by jpcirqueira** [UnBArqDsw/2020.1_G7_TCM#28]
### Descrição
Revisar todos os documentos antes da primeira entrega (11/09)

### Documento a serem revisados
- [x] 5w2h
- [x] Brainstorm
- [x] Cronograma
- [x] Backlog.md
- [x] Diagrama de causa e efeito
- [x] Documento de visao
- [x] Entrevista
- [x] Lexico
- [x] Mapa mental
- [x] Metodologia
- [x] Observação
- [x] Personas
- [x] Plano de risco
- [x] Plano de custo
- [x] Prototipo
- [x] Rich picture
-

**Comment by RCristyan** [comment]
Todos os documentos foram revisados individualmente, alguns pequenos problemas foram corrigidos e está tudo pronto para a entrega de sexta, 11/09.
