### ISSUE TITLE
Diagrama de componentes

### ISSUE THREAD

**Issue by MoacirMSJ** [UnBArqDsw/2020.1_G7_TCM#32]
Elaborar o diagrama de componentes para a aplicação.

**Comment by MoacirMSJ** [comment]
Revisão:
i.Há uma referência do diagrama de sequência no documento, talvez tenha sido por engano.
ii. O diagrama representa as relações entre os componentes da aplicação, talvez seja interessante a utilização de portas para representar o ponto de interações entre as partes internas.
iii. Contém erros de gramática na introdução, conclusão e talvez no link da metodologia "lucidChartMenu".

**Comment by RCristyan** [comment]
Os tópicos observados na revisão foram corrigidos, o documento e o diagrama estão prontos para serem aprovados.
