### ISSUE TITLE
Diagrama de sequencia

### ISSUE THREAD

**Issue by lucasA27** [UnBArqDsw/2020.1_G7_TCM#36]
Elaborar o diagrama de sequencia para a aplicação.

**Comment by MatheusEstanislau** [comment]
Documento foi finalizado aguardando review da equipe para o fechamento da issue

**Comment by RCristyan** [comment]
O documento e os diagramas foram revisados, gostaria de fazer algumas observações:

- O título do terceiro diagrama no documento não faz muito sentido. Está "Gerenciado do torneio". Talvez os autores pensaram em "Gerenciador do torneio" ou "Gerência do torneio"?
- Na figura abaixo é possível identificar uma inconsistência que ocorre nos três diagramas, onde "Front -end" tem um espaço desnecessário entre o hífen.
![image](https://user-images.githubusercontent.com/39436190/94367347-7c08d900-00b4-11eb-8a4d-c9b96b0256fd.png)
- No terceiro diagrama há um erro, pois o plural de "match" é "matches"
![image](https://user-images.githubusercontent.com/39436190/94367448-457f8e00-00b5-11eb-82e5-742fde5ae9ee.png)
- O padrão dos atributos de classe foram definidos como snake_case, e não camelCase, portanto os três casos no terceiro diagrama estão incorretos. Deveriam ser "tournament_id" (e não tourment) e "match_id".
![image](https://user-images.githubusercontent.com/39436190/94367585-19b0d800-00b6-11eb-930f-2c0f6c634e4f.png)
![image](https://user-images.githubusercontent.com/39436190/94367508-94c5be80-00b5-11eb-9c3c-1d350be23eca.png)
![image](https://user-images.githubusercontent.com/39436190/94367514-9e4f2680-00b5-11eb-9083-795d64d3aa65.png)

Tirando estas pequenas observações, o diagrama ficou muito bom. Após as correções ele estará pronto para entrega da disciplina.

**Comment by RCristyan** [comment]
Os problemas encontrados foram corrigidos. O documento e os diagramas estão prontos para a entrega.
