### ISSUE TITLE
Revisar diagrama de componentes

### ISSUE THREAD

**Issue by MatheusEstanislau** [UnBArqDsw/2020.1_G7_TCM#59]
### Descrição
 Revisar interfaces incluídas no diagrama de componentes

**Comment by RCristyan** [comment]
O diagrama de componentes foi modificado e esse é seu estado atual:
![image](https://user-images.githubusercontent.com/39436190/96281343-95b08880-0faf-11eb-9186-914962210f21.png)
 
Caso o diagrama de classes seja modificado, deveremos atualizar o diagrama de componentes.
