### ISSUE TITLE
[DOC]Diagrama de Estados

### ISSUE THREAD

**Issue by MatheusEstanislau** [UnBArqDsw/2020.1_G7_TCM#62]
### Descrição
Revisar nomes no diagrama de estados

### Coisas a se fazer
- [x] Revisar documento

**Comment by RCristyan** [comment]
Os nomes de alguns estados foram alterados de acordo com as observações da professora na avaliação 2. Segue a versão 1.1 do diagrama de estados de gerenciar torneio:

![diagrama_de_estados(gerenciar torneio)_v1 1](https://user-images.githubusercontent.com/39436190/95667647-52819000-0b3f-11eb-9d71-2280f62bcf05.png)

Este novo diagrama também foi adicionado ao documento de diagrama de estados:
https://github.com/UnBArqDsw/2020.1_G7_TCM/blob/master/docs/modelagem/diagrama_de_estados.md
